version: "3.3"
services:
  php:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:latest
    links:
      - php
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx/

  db:
    image: postgres:latest
    env_file:
      - app/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5432:5432
